name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  check-lint-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS version
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Clean installation
        run: npm ci
      - name: Check linter
        run: npm run lint
      - name: Run tests
        run: npm test
